#!/bin/bash
# PostToolUse hook to auto-save Plan mode analysis to AI-Notes

set -euo pipefail

# Read hook input JSON from stdin
input=$(cat)

# Debug output (uncomment if needed)
# echo "$input" >> ~/.claude/hooks/debug.log

# Extract tool name and response
tool_name=$(echo "$input" | jq -r '.tool_name // ""')
subagent_type=$(echo "$input" | jq -r '.tool_input.subagent_type // ""')
description=$(echo "$input" | jq -r '.tool_input.description // ""')
tool_response=$(echo "$input" | jq -r '.tool_response // ""')

# Only process Task tool invocations
if [[ "$tool_name" != "Task" ]]; then
  exit 0
fi

# Skip if not Plan agent (other agents can be captured if needed)
if [[ "$subagent_type" != "Plan" ]]; then
  exit 0
fi

# Generate output path using ai-notes skill
# Use description to generate filename
safe_description=$(echo "$description" | tr ' ' '-' | tr -cd '[:alnum:]-')
output_file=$(deno run --allow-env=HOME --allow-read \
  ~/.claude/skills/ai-notes/notes.ts generate "plan-${safe_description}" 2>/dev/null)

# Fallback if deno command fails
if [[ -z "$output_file" ]] || [[ ! "$output_file" =~ ^/ ]]; then
  timestamp=$(date +%Y-%m-%d-%H%M)
  output_file=~/Compost/AI-Notes/plan-${timestamp}.md
fi

# Create output directory
mkdir -p "$(dirname "$output_file")"

# Save as Markdown
cat > "$output_file" <<EOF
# Plan Mode Analysis: ${description}

## Analysis Date
$(date '+%Y-%m-%d %H:%M:%S')

## Analysis Content

${tool_response}

---
*Auto-generated by PostToolUse hook*
EOF

# Success message (optional)
echo "✓ Plan analysis saved to: $output_file" >&2

exit 0
