# -*- coding: utf-8 -*-
# ひらかな・カタカナ・半角カナ入力モードでのキー入力変換マップ
# UTF-8 + LF (BOMなし) で記述してください。
# #で始まる行は無視されます。

# 自分でカスタマイズして使用したい場合はこのファイルを
# ~/Library/Containers/net.mtgto.inputmethod.macSKK/Data/Documents/Settings/kana-rule.conf
# に置いてください。
# デフォルトのルールとの差分だけを記述することも可能です。
# その場合は #!use-default だけ含む行をどこかに置いてください。

# 各行はカンマ区切りで2-5要素記述する必要があります。
# 各要素でカンマを使用したい場合は &comma; と記述してください。
# 第一要素でシャープを使用したい場合は &sharp; と記述してください。
# 1つ目: ローマ字入力で確定入力されるまでに入力される文字列を指定してください。
# 2つ目: ひらがなモードで入力される文字を指定してください。
# 3つ目: カタカナモードで入力される文字を指定してください。
# 省略時はひらがなモードで入力される文字を自動でカタカナに変換します。
# 記号などはカタカナに変換できないのでそのまま使用されます。
# 4つ目: 半角カナ入力モードで入力される文字を指定してください。
# 省略時はひらがなモードで入力される文字を自動で半角に変換します。
# 5つ目: 未確定のローマ字として残す文字を指定してください。
# 省略された場合は未確定文字として残るローマ字がないことを表します。
# 例えば "tt,っ,ッ,ｯ,t" という行がある場合、
# "tt" と入力したときには "っ" をひらがなモードで入力し "t" が未確定のローマ字として残ります。
#
# 2つ目の要素に "<okuri>" を含めると、送り仮名付きのルールを定義できます。
# 例えば "gq,が<okuri>い" という行がある場合:
# - シフトなしで gq と入力すると "がい" がそのまま入力されます。
# - シフトを押しながら入力すると "が" を読み部分、"い" を送り仮名として辞書変換を開始します。
# AZIKなどで「願い(ねがい)」を NegQ (4打鍵) で変換開始できるようになります。

#!use-default

# 全角で入力したい記号
-,ー
&comma;,、
.,。
[,「
],」
(,（
),）
?,？
!,！
@,＠
%,％
&,＆
*,＊
+,＋
=,＝
:,：

# 特殊な入力
z-,〜
z&comma;,‥
z.,…
z/,・
zh,←
zj,↓
zk,↑
zl,→
z ,　
z[,『
z],』

# 2つ目の要素を "<shift>" + 入力したいキーで書くと、特殊な設定としてシフトキーを押しながら入力したと見做す
# JIS配列の "+" や英字配列の ":" のように、シフトキーで変わるキーを元のキーをシフト入力したと見做すことができる
# 例えばAZIKで ; を「っ」入力に割り当てている場合に下記のような設定をすることで送り仮名の「っ」を入力できる
# JIS配列
#+,<shift>;
# US配列
#:,<shift>;
