nnoremap 1 :<C-u>Rapidfire F1<CR>
nnoremap 2 :<C-u>Rapidfire F2<CR>
nnoremap 3 :<C-u>Rapidfire F3<CR>
nnoremap 4 :<C-u>Rapidfire F4<CR>
nnoremap 5 :<C-u>Rapidfire F5<CR>
nnoremap 6 :<C-u>Rapidfire F6<CR>
nnoremap 7 :<C-u>Rapidfire F7<CR>
nnoremap 8 :<C-u>Rapidfire F8<CR>
nnoremap 9 :<C-u>Rapidfire F9<CR>
