setl spell
setl autoindent
setl textwidth=0
setl colorcolumn=80
setl expandtab
setl softtabstop=4
setl shiftwidth=4
setl formatoptions&
setl formatoptions+=tqn
setl formatlistpat=^\\s*\\(\\d\\+\\\|[a-z]\\)[\\].)]\\s*
